### ISSUE TITLE
restart php7-apache container is causing issues

### ISSUE THREAD

**Issue by lorenzvth7** [tagplus5/dockerfiles#1]
Started the container and mounted my index.
`docker run -d -it -v /root/test/:/var/www/html -p 80:80 tagplus5/php7-apache`

Working fine. Zou my index.htm on my IP:80.
But the issue is when I want to restart the container (or start the container with `--restart=always`)?

Check:

```
# docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
14847ac8afdc        tagplus5/php7-apache   "/bin/sh -c '/usr/sbi"   15 seconds ago      Up 13 seconds       0.0.0.0:80->80/tcp       naughty_meninsky
```

This is fine. But now restart (to fake a restart of a server with a container which is using `--restart=always`)
# docker restart 14847ac8afdc

Container isn't running anymore:

```
# docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS                     PORTS                    NAMES
14847ac8afdc        tagplus5/php7-apache   "/bin/sh -c '/usr/sbi"   About a minute ago   Exited (0) 7 seconds ago                            naughty_meninsky
```

logs:

```
# docker logs 14847ac8afdc
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
httpd (pid 7) already running
```

httpd is still running in the restarted container and it tries to start a new one.

**Comment by tagplus5** [comment]
You cannot use `-d` option with `-it` option [Detached vs foreground](https://docs.docker.com/engine/reference/run/#detached-vs-foreground)

If you want to create the auto restart container, try this
`docker run -d --restart=always --name testsite -v /root/test/:/var/www/html -p 80:80 tagplus5/php7-apache`
Then you cannot restart or stop this container, you can only kill container `docker kill testsite`

If you want to manual start, stop, restart contrainer, you may not use `--restart` option

**Comment by lorenzvth7** [comment]
The -d and -it was a mistake indeed.
I started: `docker run -d --restart=always --name testsite -v /root/test/:/var/www/html -p 80:80 tagplus5/php7-apache`

But after restarting the Status of my container: `Restarting (0) 53 seconds ago`
It's going in an restarting loop. The app is not reachable anymore on my browser.

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS                          PORTS                                                       NAMES
92cab19e5341        tagplus5/php7-apache   "/bin/sh -c '/usr/sbi"   About a minute ago   Restarting (0) 53 seconds ago   0.0.0.0:80->80/tcp                                          testsite
```

Docker logs show:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
httpd (pid 7) already running
```

**Comment by tagplus5** [comment]
I fix this. The problem was in the `ServerName` and `apache2.pid`.

**Comment by junguchina** [comment]
@lorenzvth7 @tagplus5 
I missed the same issue when start apache in docker.
The logs output:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
httpd (pid 1) already running
```
It's going in an restarting loop. 
How to resolve this issue,could you provide the solution?
Thank you so much.

**Comment by tagplus5** [comment]
@junguchina try to pull new image
```
docker pull tagplus5/php7-apache
```
Show me, how can i reproduce this error, please.
I check 
```
docker run -d --restart=always --name testsite -v /root/test/:/var/www/html -p 80:80 tagplus5/php7-apache
```
then 
```
docker restart testsite
```
```
docker stop testsite
```
```
docker start testsite
```
works without any issue
